service: brand-creator-website-campaigns-api
runtime: python311
entrypoint: uvicorn app:app --host=0.0.0.0 --port=${PORT}

instance_class: F2

# Environment variables with your actual values
env_variables:
  SUPABASE_URL: "https://ldlxyyctxylgmstfqlzh.supabase.co"
  SUPABASE_SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkbHh5eWN0eHlsZ21zdGZxbHpoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTA0NDEwMSwiZXhwIjoyMDU2NjIwMTAxfQ.7m2VEaoRI4tur6BxBseL-jczHULlLgVt0xV0RYJb5BM"
  DATABASE_URL: "postgresql://postgres.ldlxyyctxylgmstfqlzh:299976387y!@aws-0-us-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true&prepared_statements=false"
  DIRECT_URL: "postgresql://postgres.ldlxyyctxylgmstfqlzh:299976387y!@aws-0-us-west-1.pooler.supabase.com:5432/postgres"
  NEXTAUTH_SECRET: "5b3d1f27e1523d6fc035cb070d86660373d67d50313e774a68d9eb6612ceb029"
  NEXTAUTH_URL: "http://localhost:3000"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_USER: "info@borderxmedia.com"
  SMTP_PASSWORD: "kvdtzvwjivhsjkgo"
  NEXT_PUBLIC_APP_URL: "https://borderx.net"
  TIKTOK_ACCESS_TOKEN: "501451aac8e52709146ce1791efe81b15c26cbfe"
  TIKTOK_TCM_ACCOUNT_ID: "7491077961832202247"
  CAMPAIGNS_API_URL: "http://localhost:5000"
  TTVERIFICATION_API_URL: "https://brand-creator-website-python-api-dot-overseabiz-453023.wl.r.appspot.com/"

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 3
  min_idle_instances: 0
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 50

# Request handlers
handlers:
- url: /.*
  script: auto
  secure: always