service: brand-creator-website-campaigns-api
runtime: python311
env: standard
instance_class: F2

handlers:
  - url: /.*
    script: auto
    secure: always
  - url: .*
    script: auto

env_variables:
  # Database Configuration
  DATABASE_URL: >-
    postgresql://postgres.ldlxyyctxylgmstfqlzh:299976387y!@aws-0-us-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true&prepared_statements=false
  DIRECT_URL: >-
    postgresql://postgres.ldlxyyctxylgmstfqlzh:299976387y!@aws-0-us-west-1.pooler.supabase.com:5432/postgres
  
  # Supabase Configuration
  SUPABASE_URL: 'https://ldlxyyctxylgmstfqlzh.supabase.co'
  SUPABASE_SERVICE_KEY: >-
    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkbHh5eWN0eHlsZ21zdGZxbHpoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTA0NDEwMSwiZXhwIjoyMDU2NjIwMTAxfQ.7m2VEaoRI4tur6BxBseL-jczHULlLgVt0xV0RYJb5BM
  
  # SMTP Configuration
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: '587'
  SMTP_SECURE: 'false'
  SMTP_USER: info@borderxmedia.com
  SMTP_PASSWORD: kvdtzvwjivhsjkgo
  
  # TikTok API Configuration
  TIKTOK_ACCESS_TOKEN: "501451aac8e52709146ce1791efe81b15c26cbfe"
  TIKTOK_TCM_ACCOUNT_ID: "7491077961832202247"
  
  # App Configuration
  NEXT_PUBLIC_APP_URL: "https://cricher.ai"
  
  # API URLs
  CAMPAIGNS_API_URL: "https://brand-creator-website-campaigns-api-dot-overseabiz-453023.wl.r.appspot.com"
  TTVERIFICATION_API_URL: "https://brand-creator-website-python-api-dot-overseabiz-453023.wl.r.appspot.com/"

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 50
  target_throughput_utilization: 0.65
  target_cpu_utilization: 0.65
  max_instances: 3

service_account: overseabiz-453023@appspot.gserviceaccount.com