service: campaign-upload-api
runtime: python311
entrypoint: uvicorn app:app --host=0.0.0.0 --port=${PORT}

instance_class: F2

# Environment variables
env_variables:
  SUPABASE_URL: "https://ldlxyyctxylgmstfqlzh.supabase.co"
  SUPABASE_SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkbHh5eWN0eHlsZ21zdGZxbHpoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTA0NDEwMSwiZXhwIjoyMDU2NjIwMTAxfQ.7m2VEaoRI4tur6BxBseL-jczHULlLgVt0xV0RYJb5BM"

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_cpu_utilization: 0.65
